name: EpicHoppers
description: EpicHoppers
main: com.songoda.epichoppers.EpicHoppers
softdepend:
  - ASkyBlock
  - AdvancedChests
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - EpicFarming
  - FabledSkyBlock
  - Factions
  - GriefPrevention
  - Kingdoms
  - LiquidTanks
  - PlotsSquared
  - RedProtect
  - Reserve
  - Towny
  - USkyBlock
  - UltimateStacker
  - Vault
  - WildStacker
  - WorldGuard
version: maven-version-number
author: Songoda
api-version: 1.13
commands:
  eh:
    description: View information on this plugin.
    default: true
    aliases: [ EpicHoppers ]
    usage: /eh
